cleanupUnusedCatalogs: true
linkWorkspacePackages: true
preferWorkspacePackages: true

packages:
  - integrations/*
  - packages/*

catalog:
  '@changesets/cli': ^2.29.7
  '@commitlint/parse': ^20.0.0
  '@eslint/js': ^9.37.0
  '@stylistic/eslint-plugin': ^5.4.0
  '@svitejs/changesets-changelog-github-compact': ^1.2.0
  '@tanstack/query-core': ^5.90.2
  '@types/eslint': ^9.6.1
  '@types/jsonfile': ^6.1.4
  '@types/node': ^24.5.2
  '@types/react': ^19.2.2
  '@types/react-dom': ^19.2.1
  '@types/semver': ^7.7.1
  '@vitejs/plugin-react': ^5.0.4
  '@vitejs/plugin-vue': ^6.0.1
  eslint: ^9.37.0
  eslint-plugin-import-x: ^4.16.1
  eslint-plugin-n: ^17.23.1
  globals: ^16.4.0
  jsdom: ^27.0.0
  jsonfile: ^6.2.0
  markdown-link-extractor: ^4.0.2
  nx: ^21.6.4
  prettier: ^3.6.2
  publint: ^0.3.14
  react: ^19.2.0
  react-dom: ^19.2.0
  rollup-plugin-preserve-directives: ^0.4.0
  semver: ^7.7.3
  sherif: ^1.6.1
  simple-git: ^3.28.0
  tinyglobby: ^0.2.15
  type-fest: ^5.0.1
  typedoc: 0.28.14
  typedoc-plugin-frontmatter: 1.3.0
  typedoc-plugin-markdown: 4.9.0
  typescript: ^5.9.2
  typescript-eslint: ^8.46.0
  vite: ^7.1.9
  vite-plugin-dts: 4.2.3
  vite-plugin-externalize-deps: ^0.10.0
  vite-tsconfig-paths: ^5.1.4
  vitest: ^3.2.4
  vue: ^3.5.22
  vue-eslint-parser: ^10.2.0
