cleanupUnusedCatalogs: true
linkWorkspacePackages: true
preferWorkspacePackages: true

packages:
  - integrations/*
  - packages/*

catalog:
  '@arethetypeswrong/core': ^0.18.2
  '@changesets/cli': ^2.29.8
  '@commitlint/parse': ^20.4.1
  '@eslint/js': ^10.0.1
  '@stylistic/eslint-plugin': ^5.7.1
  '@svitejs/changesets-changelog-github-compact': ^1.2.0
  '@tanstack/query-core': ^5.90.20
  '@types/eslint': ^9.6.1
  '@types/jsonfile': ^6.1.4
  '@types/node': ^24.10.1
  '@types/react': ^19.2.13
  '@types/react-dom': ^19.2.3
  '@types/semver': ^7.7.1
  '@vitejs/plugin-react': ^5.1.3
  '@vitejs/plugin-vue': ^6.0.4
  eslint: ^10.0.0
  eslint-plugin-import-x: ^4.16.1
  eslint-plugin-n: ^17.23.2
  globals: ^17.3.0
  jiti: ^2.6.1
  jsdom: ^28.0.0
  jsonfile: ^6.2.0
  markdown-link-extractor: ^4.0.3
  nx: 22.5.0
  premove: ^4.0.0
  prettier: ^3.8.1
  publint: ^0.3.17
  react: ^19.2.4
  react-dom: ^19.2.4
  rollup-plugin-preserve-directives: ^0.4.0
  semver: ^7.7.4
  sherif: ^1.10.0
  simple-git: ^3.30.0
  tinyglobby: ^0.2.15
  tsdown: ^0.20.3
  type-fest: ^5.4.4
  typedoc: 0.28.14
  typedoc-plugin-frontmatter: 1.3.0
  typedoc-plugin-markdown: 4.9.0
  typescript: 6.0.0-beta
  typescript-eslint: ^8.55.0
  vite: ^7.3.1
  vite-plugin-dts: 4.2.3
  vite-plugin-externalize-deps: ^0.10.0
  vite-tsconfig-paths: ^5.1.4
  vitest: ^4.0.18
  vue: ^3.5.27
  vue-eslint-parser: ^10.2.0
  oxlint: "^1.47.0"
