cleanupUnusedCatalogs: true
linkWorkspacePackages: true
preferWorkspacePackages: true

packages:
  - integrations/*
  - packages/*

catalog:
  '@arethetypeswrong/core': ^0.18.2
  '@changesets/cli': ^2.29.8
  '@commitlint/parse': ^20.3.1
  '@eslint/js': ^9.39.2
  '@stylistic/eslint-plugin': ^5.7.0
  '@svitejs/changesets-changelog-github-compact': ^1.2.0
  '@tanstack/query-core': ^5.90.18
  '@types/eslint': ^9.6.1
  '@types/jsonfile': ^6.1.4
  '@types/node': ^24.10.1
  '@types/react': ^19.2.8
  '@types/react-dom': ^19.2.3
  '@types/semver': ^7.7.1
  '@vitejs/plugin-react': ^5.1.2
  '@vitejs/plugin-vue': ^6.0.3
  eslint: ^9.39.2
  eslint-plugin-import-x: ^4.16.1
  eslint-plugin-n: ^17.23.2
  globals: ^16.5.0
  jiti: ^2.6.1
  jsdom: ^27.4.0
  jsonfile: ^6.2.0
  markdown-link-extractor: ^4.0.3
  nx: 22.3.3
  premove: ^4.0.0
  prettier: ^3.8.0
  publint: ^0.3.16
  react: ^19.2.3
  react-dom: ^19.2.3
  rollup-plugin-preserve-directives: ^0.4.0
  semver: ^7.7.3
  sherif: ^1.9.0
  simple-git: ^3.30.0
  tinyglobby: ^0.2.15
  tsdown: ^0.19.0
  type-fest: ^5.4.1
  typedoc: 0.28.14
  typedoc-plugin-frontmatter: 1.3.0
  typedoc-plugin-markdown: 4.9.0
  typescript: ^5.9.2
  typescript-eslint: ^8.53.0
  vite: ^7.3.1
  vite-plugin-dts: 4.2.3
  vite-plugin-externalize-deps: ^0.10.0
  vite-tsconfig-paths: ^5.1.4
  vitest: ^4.0.17
  vue: ^3.5.26
  vue-eslint-parser: ^10.2.0
