packages:
  - integrations/*
  - packages/*

catalog:
  '@commitlint/parse': ^19.5.0
  '@eslint/js': ^9.20.0
  '@stylistic/eslint-plugin-js': ^3.1.0
  '@tanstack/query-core': ^5.66.0
  '@types/eslint': ^9.6.1
  '@types/interpret': ^1.1.3
  '@types/jsonfile': ^6.1.4
  '@types/liftoff': ^4.0.3
  '@types/minimist': ^1.2.5
  '@types/node': ^22.13.1
  '@types/react': ^19.0.8
  '@types/react-dom': ^19.0.3
  '@types/semver': ^7.5.8
  '@types/v8flags': ^3.1.3
  '@vitejs/plugin-react': ^4.3.4
  '@vitejs/plugin-vue': ^5.2.1
  commander: ^13.1.0
  esbuild-register: ^3.6.0
  eslint: ^9.20.1
  eslint-plugin-import-x: ^4.6.1
  eslint-plugin-n: ^17.15.1
  globals: ^15.14.0
  interpret: ^3.1.1
  jsdom: ^26.0.0
  jsonfile: ^6.1.0
  liftoff: ^5.0.0
  minimist: ^1.2.8
  nx: ^20.4.2
  prettier: ^3.5.0
  publint: ^0.3.4
  react: ^19.0.0
  react-dom: ^19.0.0
  rollup-plugin-preserve-directives: ^0.4.0
  semver: ^7.7.1
  sherif: ^1.3.0
  simple-git: ^3.27.0
  type-fest: ^4.34.1
  typedoc: ^0.27.7
  typedoc-plugin-frontmatter: ^1.1.2
  typedoc-plugin-markdown: ^4.4.2
  typescript: ^5.7.3
  typescript-eslint: ^8.24.0
  v8flags: ^4.0.1
  vite: ^6.1.0
  vite-plugin-dts: ^4.5.0
  vite-plugin-externalize-deps: ^0.9.0
  vite-tsconfig-paths: ^5.1.4
  vitest: ^3.0.5
  vue: ^3.5.13
  vue-eslint-parser: ^9.4.3
