packages:
  - integrations/*
  - packages/*

catalog:
  '@changesets/cli': ^2.29.5
  '@commitlint/parse': ^19.8.1
  '@eslint/js': ^9.32.0
  '@stylistic/eslint-plugin': ^5.2.2
  '@svitejs/changesets-changelog-github-compact': ^1.2.0
  '@tanstack/query-core': ^5.83.1
  '@types/eslint': ^9.6.1
  '@types/jsonfile': ^6.1.4
  '@types/node': ^24.0.15
  '@types/react': ^19.1.9
  '@types/react-dom': ^19.1.7
  '@types/semver': ^7.7.0
  '@vitejs/plugin-react': ^4.7.0
  '@vitejs/plugin-vue': ^5.2.4
  eslint: ^9.32.0
  eslint-plugin-import-x: ^4.16.1
  eslint-plugin-n: ^17.21.3
  eslint-plugin-pnpm: ^1.1.0
  globals: ^16.3.0
  jsdom: ^26.1.0
  jsonc-eslint-parser: ^2.4.0
  jsonfile: ^6.1.0
  markdown-link-extractor: ^4.0.2
  nx: ^21.3.11
  prettier: ^3.6.2
  publint: ^0.3.12
  react: ^19.1.1
  react-dom: ^19.1.1
  rollup-plugin-preserve-directives: ^0.4.0
  semver: ^7.7.2
  sherif: ^1.6.1
  simple-git: ^3.28.0
  tinyglobby: ^0.2.14
  type-fest: ^4.41.0
  typedoc: 0.27.9
  typedoc-plugin-frontmatter: 1.2.1
  typedoc-plugin-markdown: 4.4.2
  typescript: ^5.8.2
  typescript-eslint: ^8.38.0
  vite: ^6.3.5
  vite-plugin-dts: 4.2.3
  vite-plugin-externalize-deps: ^0.9.0
  vite-tsconfig-paths: ^5.1.4
  vitest: ^3.2.4
  vue: ^3.5.18
  vue-eslint-parser: ^10.2.0
  yaml-eslint-parser: ^1.3.0
