packages:
  - integrations/*
  - packages/*

catalog:
  '@changesets/cli': ^2.28.1
  '@commitlint/parse': ^19.8.0
  '@eslint/js': ^9.24.0
  '@stylistic/eslint-plugin-js': ^4.2.0
  '@svitejs/changesets-changelog-github-compact': ^1.2.0
  '@tanstack/query-core': ^5.74.0
  '@types/eslint': ^9.6.1
  '@types/interpret': ^1.1.3
  '@types/jsonfile': ^6.1.4
  '@types/liftoff': ^4.0.3
  '@types/minimist': ^1.2.5
  '@types/node': ^22.13.6
  '@types/react': ^19.1.1
  '@types/react-dom': ^19.1.2
  '@types/semver': ^7.7.0
  '@types/v8flags': ^3.1.3
  '@vitejs/plugin-react': ^4.3.4
  '@vitejs/plugin-vue': ^5.2.3
  commander: ^13.1.0
  esbuild-register: ^3.6.0
  eslint: ^9.24.0
  eslint-plugin-import-x: ^4.10.3
  eslint-plugin-n: ^17.17.0
  globals: ^16.0.0
  interpret: ^3.1.1
  jsdom: ^26.1.0
  jsonfile: ^6.1.0
  liftoff: ^5.0.0
  minimist: ^1.2.8
  nx: ^20.7.2
  prettier: ^3.5.3
  publint: ^0.3.11
  react: ^19.1.0
  react-dom: ^19.1.0
  rollup-plugin-preserve-directives: ^0.4.0
  semver: ^7.7.1
  sherif: ^1.5.0
  simple-git: ^3.27.0
  type-fest: ^4.39.1
  typedoc: 0.27.9
  typedoc-plugin-frontmatter: 1.2.1
  typedoc-plugin-markdown: 4.4.2
  typescript: ^5.8.2
  typescript-eslint: ^8.29.1
  v8flags: ^4.0.1
  vite: ^6.2.6
  vite-plugin-dts: 4.2.3
  vite-plugin-externalize-deps: ^0.9.0
  vite-tsconfig-paths: ^5.1.4
  vitest: ^3.1.1
  vue: ^3.5.13
  vue-eslint-parser: ^10.1.3
