name: Comment on PRs about release
description: Automatically comments on PRs when they are included in a release
inputs:
  published-packages:
    description: 'JSON string of published packages from changesets/action'
    required: true
runs:
  using: composite
  steps:
    - name: Comment on PRs
      shell: bash
      env:
        PUBLISHED_PACKAGES: ${{ inputs.published-packages }}
      run: |
        npx tsx ${{ github.action_path }}/comment-on-release.ts
