name: Setup Tools
description: Action that sets up Node and pnpm
runs:
  using: composite
  steps:
    - name: Setup Vite+
      uses: voidzero-dev/setup-vp@2dec1e33f4ab2c6d5bce1b0c4607961bb1a3f7a1 # v1.12.0
      with:
        node-version-file: .nvmrc
        run-install: true
        cache: false
    - name: Setup pnpm
      run: vp install -g pnpm
