name: Setup Tools
description: Action that sets up Node and pnpm
runs:
  using: composite
  steps:
    - name: Setup Vite+
      uses: voidzero-dev/setup-vp@9fd26ff49f9b5e6276c2b493da4454ad4527f7f4 # v1.20.0
      with:
        node-version-file: .nvmrc
        run-install: true
        cache: false
    - name: Setup pnpm
      shell: bash
      run: vp install -g pnpm
