name: Setup Tools
description: Action that sets up Node and pnpm
runs:
  using: composite
  steps:
    - name: Setup Vite+
      uses: voidzero-dev/setup-vp@68f39c78aaf39be468cabd2afb09c162574c84af # v1.21.2
      with:
        node-version-file: .nvmrc
        run-install: true
        cache: false
    - name: Setup pnpm
      shell: bash
      run: vp install -g pnpm
