import { MarkdownPageEvent } from 'typedoc-plugin-markdown'
import type { MarkdownApplication } from 'typedoc-plugin-markdown'

export function load(app: MarkdownApplication): void {
  // Add `id` and `title` to frontmatter
  app.renderer.on(MarkdownPageEvent.BEGIN, (page: MarkdownPageEvent) => {
    page.frontmatter = {
      id: page.model.name,
      title: page.model.name,
    }
    page.contents =
      '<!-- DO NOT EDIT: this page is autogenerated from the type comments -->\n\n'
  })
}
