name: Preview

on:
  pull_request:
  push:
    branches-ignore: [main, alpha, beta]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

permissions:
  contents: read

jobs:
  preview:
    name: Preview
    if: github.repository_owner == 'TanStack'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
      - name: Setup Tools
        uses: ./.github/setup
      - name: Publish Previews
        run: pnpx pkg-pr-new publish --pnpm --compact './packages/*' --no-template
