name: Release

on:
  push:
    branches: [main, alpha, beta]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

permissions:
  contents: read

jobs:
  release:
    name: Release
    if: github.repository_owner == 'TanStack'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Tools
        uses: ./.github/setup
      - name: Run Tests
        run: pnpm run test:ci
      - name: Run Changesets (version or publish)
        id: changesets
        uses: changesets/action@a45c4d594aa4e2c509dc14a9f2b3b67ba3780d0d # v1.9.0
        with:
          version: pnpm run changeset:version
          publish: pnpm run changeset:publish
          commit: 'ci: Version Packages'
          title: 'ci: Version Packages'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Comment on PRs and issues about release
        if: steps.changesets.outputs.published == 'true'
        uses: ./.github/comment-on-release
        with:
          published-packages: ${{ steps.changesets.outputs.publishedPackages }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
